development:
  stripe_secret_key: 'sk_test_51MIAsySCpew2dGdAKstDBgRiZIGtvhPrWCRDTKnopqrmVnU0OiATDvJlR5VxWmGQL05B7pfgMHuCQeCab2jgxLRk00HnmAf2sq'
  stripe_publishable_key: 'pk_test_51MIAsySCpew2dGdAXyzP0ZCwxyV87a52gkU0NfKFFRVetbH6YsUgcqRzN7ANP5dklS5xfU6SLKDnfFJ0fFlZuPkV00ND1vITvu'